import type { AnchorRef, BookAnchor, BookClaim, Claim, Confidence, SupportLevel } from "./types.js";
import { parseAnchorRef, schemeOf, toSeconds } from "./anchors.js";

/**
 * Parser for the markdown ledger. Two layers:
 *
 * 1. `parseBookLedger` — a mechanical, byte-compatible port of
 *    `build_evidence.py::parse_ledger()`. Its regexes ARE the spec; the Python
 *    script is kept as the conformance oracle (see the conformance test suite,
 *    which compares against JSON generated by the real Python).
 *
 * 2. `parseLedger` — the generalized `.ledger/claims.md` parser. Same block
 *    grammar (`## N) claim text`), but anchors may be any of the six schemes
 *    written as `**Anchor:** \`<uri>\` · confidence: <c>`. Bare 11-char video
 *    anchors (the book's native format) are still accepted and normalized to
 *    `yt://` so the 794-video corpus parses unchanged.
 */

// ── regex grammar (ported 1:1 from build_evidence.py) ──────────────────────

const CLAIM_RE = /^##\s+(\d+)\)\s+(.+?)\s*$/gm;
const SUPPORT_RE = /\*\*Support level:\*\*\s*([A-Za-z]+)/;
const CANDIDATE_RE = /\*\*Candidate chapters:\*\*\s*([0-9,\s]+)/;
const SCOPES_RE = /\*\*(?:Candidate scopes|Scopes):\*\*\s*(.+)$/m;
const CAVEATS_RE = /\*\*Caveats(?: \/ counterpoints)?:\*\*\s*(.+)$/m;
const SOURCE_BULLET_RE = /^\s*-\s+\[\[([^\]]+)\]\]/;
const BOOK_ANCHOR_RE = new RegExp(
  String.raw`\*\*Anchor:\*\*\s*` +
    "`([A-Za-z0-9_-]{11})`" +
    String.raw`\s*(\d\d:\d\d:\d\d\.\d\d\d)\s*(?:→|-{1,2}>)\s*(\d\d:\d\d:\d\d\.\d\d\d)` +
    String.raw`.*?confidence:\s*(\w+)`,
);
const URI_ANCHOR_RE = /\*\*Anchor:\*\*\s*`([a-z]+:\/\/[^`]+)`(?:.*?confidence:\s*(\w+))?/;
const QUOTE_RE = /\*\*Quote:\*\*\s*"(.+)"\s*$/;
const LABEL_BULLET_RE = /^\s*-\s+(?:\[\[([^\]]+)\]\]|\*\*Source:\*\*\s*(.+?)\s*$)/;

interface ClaimBlock {
  number: string;
  text: string;
  body: string;
}

function* claimBlocks(text: string): Generator<ClaimBlock> {
  const matches = [...text.matchAll(CLAIM_RE)];
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]!;
    const end = i + 1 < matches.length ? matches[i + 1]!.index! : text.length;
    yield {
      number: m[1]!,
      text: m[2]!.trim(),
      body: text.slice(m.index! + m[0].length, end),
    };
  }
}

function bulletLabel(inner: string): string {
  return inner.includes("|") ? inner.slice(inner.indexOf("|") + 1).trim() : inner.trim();
}

// ── layer 1: byte-compatible book parser ────────────────────────────────────

/** Port of build_evidence.py::parse_ledger — output matches the Python oracle exactly. */
export function parseBookLedger(text: string): BookClaim[] {
  const claims: BookClaim[] = [];
  for (const { number, text: claimText, body } of claimBlocks(text)) {
    const support = SUPPORT_RE.exec(body);
    const candidate = CANDIDATE_RE.exec(body);
    const chapters = candidate
      ? [...candidate[1]!.matchAll(/\d+/g)].map((n) => parseInt(n[0], 10))
      : [];
    const anchors: BookAnchor[] = [];
    let currentLabel = "";
    let pending: BookAnchor | null = null;
    for (const line of body.split("\n")) {
      const sb = SOURCE_BULLET_RE.exec(line);
      if (sb && line.trimStart().startsWith("-")) {
        currentLabel = bulletLabel(sb[1]!);
      }
      const a = BOOK_ANCHOR_RE.exec(line);
      if (a) {
        pending = {
          video_id: a[1]!,
          start: a[2]!,
          end: a[3]!,
          start_seconds: toSeconds(a[2]!),
          confidence: a[4]!.toLowerCase(),
          label: currentLabel,
        };
        continue;
      }
      const q = QUOTE_RE.exec(line);
      if (q && pending !== null) {
        pending.quote = q[1]!;
        anchors.push(pending);
        pending = null;
      }
    }
    if (anchors.length > 0) {
      claims.push({
        claim_id: `claims#${number}`,
        text: claimText,
        support_level: support ? support[1]!.toLowerCase() : "moderate",
        candidate_chapters: chapters,
        anchors,
      });
    }
  }
  return claims;
}

/** Port of build_evidence.py::build_index — chapter -> claim entries. */
export function buildBookIndex(claims: BookClaim[]): Record<string, unknown[]> {
  const index: Record<string, unknown[]> = {};
  for (const c of claims) {
    const entry = {
      claim_id: c.claim_id,
      text: c.text,
      support_level: c.support_level,
      anchors: c.anchors,
    };
    for (const chapter of c.candidate_chapters) {
      (index[String(chapter)] ??= []).push(entry);
    }
  }
  return index;
}

// ── layer 2: generalized .ledger/claims.md parser ───────────────────────────

function normalizeConfidence(raw: string | undefined): Confidence {
  const c = (raw ?? "medium").toLowerCase();
  return c === "high" || c === "low" ? c : "medium";
}

function normalizeSupport(raw: string | undefined): SupportLevel {
  const s = (raw ?? "moderate").toLowerCase();
  return s === "strong" || s === "tentative" ? s : "moderate";
}

/**
 * Parse a generalized ledger into `ledger.json` v1 claims.
 *
 * Unlike the book parser (which drops anchors lacking a quote — verbatim
 * Python behavior), scheme-URI anchors are kept without quotes; the quote is
 * what upgrades them past `medium` trust in verification.
 */
export function parseLedger(text: string): Claim[] {
  const claims: Claim[] = [];
  for (const { number, text: claimText, body } of claimBlocks(text)) {
    const support = SUPPORT_RE.exec(body);
    const chapters = CANDIDATE_RE.exec(body);
    const scopes = SCOPES_RE.exec(body);
    const caveats = CAVEATS_RE.exec(body);

    const candidate_scopes: string[] = chapters
      ? [...chapters[1]!.matchAll(/\d+/g)].map((n) => n[0])
      : scopes
        ? scopes[1]!
            .split(",")
            .map((s) => s.trim())
            .filter(Boolean)
        : [];

    const anchors: AnchorRef[] = [];
    let currentLabel = "";
    let pending: AnchorRef | null = null;

    const flush = () => {
      if (pending) anchors.push(pending);
      pending = null;
    };

    for (const line of body.split("\n")) {
      const lb = LABEL_BULLET_RE.exec(line);
      if (lb) currentLabel = lb[1] ? bulletLabel(lb[1]) : (lb[2] ?? "").trim();

      const book = BOOK_ANCHOR_RE.exec(line);
      const uri = book ? null : URI_ANCHOR_RE.exec(line);

      if (book) {
        flush();
        pending = {
          scheme: "yt",
          ref: `yt://${book[1]} ${book[2]} → ${book[3]}`,
          start_seconds: toSeconds(book[2]!),
          confidence: normalizeConfidence(book[4]),
          label: currentLabel || undefined,
        };
        continue;
      }
      if (uri) {
        const ref = uri[1]!.trim();
        const scheme = schemeOf(ref);
        if (scheme && parseAnchorRef(ref)) {
          flush();
          const parsed = parseAnchorRef(ref)!;
          pending = {
            scheme,
            ref,
            confidence: normalizeConfidence(uri[2]),
            label: currentLabel || undefined,
            ...(parsed.scheme === "yt" || parsed.scheme === "ts"
              ? { start_seconds: toSeconds(parsed.start) }
              : {}),
          };
        }
        continue;
      }
      const q = QUOTE_RE.exec(line);
      if (q && pending) {
        pending.quote = q[1]!;
        flush();
      }
    }
    flush();

    if (anchors.length > 0) {
      claims.push({
        claim_id: `claims#${number}`,
        text: claimText,
        support_level: normalizeSupport(support?.[1]),
        candidate_scopes,
        anchors,
        ...(caveats ? { caveats: caveats[1]!.trim() } : {}),
      });
    }
  }
  return claims;
}

// ── serialization back to markdown ──────────────────────────────────────────

/** Render claims back to `.ledger/claims.md` (used by `edt init` / `edt export`). */
export function renderLedgerMarkdown(claims: Claim[], title = "Claims Ledger"): string {
  const out: string[] = [`# ${title}`, ""];
  for (const c of claims) {
    const n = c.claim_id.replace(/^claims#/, "");
    out.push(`## ${n}) ${c.text}`);
    out.push(`- **Support level:** ${c.support_level}`);
    if (c.candidate_scopes.length > 0) {
      out.push(`- **Scopes:** ${c.candidate_scopes.join(", ")}`);
    }
    for (const a of c.anchors) {
      if (a.label) out.push(`- **Source:** ${a.label}`);
      out.push(`  - **Anchor:** \`${a.ref}\` · confidence: ${a.confidence}`);
      if (a.quote) out.push(`    - **Quote:** "${a.quote}"`);
    }
    if (c.caveats) out.push(`- **Caveats:** ${c.caveats}`);
    out.push("");
  }
  return out.join("\n");
}
