#!/usr/bin/env node
/**
 * event-ledger.mjs — emit a .ledger/claims.md from a YouTube talk.
 *
 * Usage:
 *   node scripts/event-ledger.mjs <video_id> "<title>" [--out examples/ledgers/<slug>]
 *
 * With OPENROUTER_API_KEY: fetches captions via yt-dlp (if installed) and mines claims.
 * Without: writes the committed sample for the well-known talk (honest labeling).
 *
 * Publish: copy the output dir to fromcopilottocolleague.com/ledgers/<slug> (manual).
 */
import { execSync, spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

/** Sample ledger: Ryan Lopopolo — Harness Engineering (OpenAI), from the book corpus.
 *  Claims extracted from ai-engineer-book-lab (54-claim flagship dataset); labeled as sample. */
const SAMPLE = {
  video_id: "am_oeAoUhew",
  title: "Harness Engineering: How to Build Software When Humans Steer, Agents Execute",
  speaker: "Ryan Lopopolo, OpenAI",
  slug: "openai-harness-engineering-2025",
  claims: [
    {
      text: "The important thing is not the code but the prompt and the guardrails that got you there",
      support: "strong",
      start: "00:06:56.800",
      end: "00:07:00.720",
      quote: "The important thing is not the code but the prompt and the guardrails that got you there.",
    },
    {
      text: "Documentation, ADRs, and breadcrumbs teach agents what good work looks like",
      support: "strong",
      start: "00:07:02.560",
      end: "00:07:09.120",
      quote: "leaving breadcrumbs, documentation, ADRs, persona oriented documentation around what a good job looks like.",
    },
    {
      text: "A good harness operationalizes giving the model text at the right time",
      support: "strong",
      start: "00:24:40.799",
      end: "00:24:45.840",
      quote: "a good harness is really operationalized around giving the model text at the right time",
    },
    {
      text: "The practical unit of harness engineering is the codebase, not isolated snippets",
      support: "strong",
      start: "00:42:21.520",
      end: "00:42:22.880",
      quote: "codebase for harness engineering",
    },
    {
      text: "Reliability comes less from model cleverness than from surrounding scaffolding",
      support: "moderate",
      start: "00:06:56.800",
      end: "00:07:00.720",
      quote: "The important thing is not the code but the prompt and the guardrails that got you there.",
      caveat: "Book synthesis claim — anchored to this talk as primary evidence.",
    },
  ],
};

function usage() {
  console.error(`Usage: node scripts/event-ledger.mjs <video_id> "<title>" [--out DIR]`);
  process.exit(1);
}

function emitLedger(meta, claims, outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  const vid = meta.video_id;
  const lines = [
    `# Event Ledger — ${meta.title}`,
    "",
    `> **Books of Truth** sample · ${meta.speaker}`,
    `> Video: [\`${vid}\`](https://www.youtube.com/watch?v=${vid})`,
    `> Generated by \`scripts/event-ledger.mjs\` · claims anchored to transcript timestamps.`,
    meta.sampleNote ? `> ${meta.sampleNote}` : "",
    "",
    "---",
    "",
  ].filter(Boolean);

  claims.forEach((c, i) => {
    lines.push(`## ${i + 1}) ${c.text}`);
    lines.push(`- **Support level:** ${c.support}`);
    lines.push(`- **Scopes:** event-ledger, ${meta.slug}`);
    lines.push(`- **Source:** ${meta.speaker}`);
    lines.push(`  - **Anchor:** \`yt://${vid} ${c.start} → ${c.end}\` · confidence: high`);
    lines.push(`    - **Quote:** "${c.quote}"`);
    if (c.caveat) lines.push(`- **Caveats:** ${c.caveat}`);
    lines.push("");
  });

  const claimsMd = lines.join("\n");
  fs.writeFileSync(path.join(outDir, "claims.md"), claimsMd);

  const ledgerJson = claims.map((c, i) => ({
    claim_id: `claims#${i + 1}`,
    text: c.text,
    support_level: c.support,
    candidate_scopes: ["event-ledger", meta.slug],
    anchors: [
      {
        scheme: "yt",
        ref: `yt://${vid} ${c.start} → ${c.end}`,
        confidence: "high",
        label: meta.speaker,
        quote: c.quote,
      },
    ],
    caveats: c.caveat ?? "",
    provenance: {
      extracted_by: "event-ledger.mjs",
      video_id: vid,
      sample: !!meta.sampleNote,
    },
  }));
  fs.writeFileSync(path.join(outDir, "ledger.json"), JSON.stringify(ledgerJson, null, 2) + "\n");

  const readme = [
    `# ${meta.title}`,
    "",
    `Event ledger for [\`${vid}\`](https://www.youtube.com/watch?v=${vid}).`,
    "",
    "## Verify (offline honesty)",
    "",
    "```bash",
    "edt verify --ledger-path claims.md   # yt:// anchors report unverifiable offline",
    "```",
    "",
    meta.sampleNote ?? "",
    "",
    "## Publish on fromcopilottocolleague.com",
    "",
    `Copy this directory to \`/ledgers/${meta.slug}/\` on the book site, or link from`,
    `[the evidence graph](https://fromcopilottocolleague.com/read/graph).`,
    "",
  ]
    .filter(Boolean)
    .join("\n");
  fs.writeFileSync(path.join(outDir, "README.md"), readme);

  console.log(`Wrote ${outDir}/claims.md (${claims.length} claims)`);
  console.log(`Wrote ${outDir}/ledger.json`);
}

async function fetchCaptions(videoId) {
  try {
    execSync("yt-dlp --version", { stdio: "ignore" });
  } catch {
    return null;
  }
  const tmp = fs.mkdtempSync(path.join(ROOT, ".tmp-event-ledger-"));
  try {
    spawnSync("yt-dlp", ["--write-auto-sub", "--sub-lang", "en", "--skip-download", "-o", `${tmp}/%(id)s`, `https://www.youtube.com/watch?v=${videoId}`], {
      stdio: "ignore",
    });
    const vtt = fs.readdirSync(tmp).find((f) => f.endsWith(".vtt"));
    if (!vtt) return null;
    return fs.readFileSync(path.join(tmp, vtt), "utf-8");
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

async function mineWithOpenRouter(vtt, title) {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) return null;
  const excerpt = vtt.slice(0, 12000);
  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "deepseek/deepseek-chat",
      messages: [
        {
          role: "system",
          content:
            "Extract 5-8 declarative claims from this transcript. Each claim MUST include a verbatim quote that appears in the text and approximate VTT timestamps. Return JSON array: [{text, support, start, end, quote}]. No fabrication.",
        },
        { role: "user", content: `Title: ${title}\n\n${excerpt}` },
      ],
      response_format: { type: "json_object" },
    }),
  });
  if (!res.ok) return null;
  const data = await res.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) return null;
  const parsed = JSON.parse(content);
  return parsed.claims ?? parsed;
}

const args = process.argv.slice(2);
if (args.length < 2) usage();
const videoId = args[0];
const title = args[1];
let outDir = path.join(ROOT, "examples/ledgers", videoId);
const outIdx = args.indexOf("--out");
if (outIdx !== -1 && args[outIdx + 1]) outDir = path.resolve(args[outIdx + 1]);

if (videoId === SAMPLE.video_id || !process.env.OPENROUTER_API_KEY) {
  emitLedger(
    {
      video_id: SAMPLE.video_id,
      title: SAMPLE.title,
      speaker: SAMPLE.speaker,
      slug: SAMPLE.slug,
      sampleNote:
        "**Sample event ledger** — claims sourced from the ai-engineer-book-lab corpus (794-video dataset). Honest labeling; not live-extracted at publish time.",
    },
    SAMPLE.claims,
    outDir.endsWith(SAMPLE.slug) ? outDir : path.join(ROOT, "examples/ledgers", SAMPLE.slug),
  );
  process.exit(0);
}

const vtt = await fetchCaptions(videoId);
if (!vtt) {
  console.error("No captions (install yt-dlp) and no sample match — exiting.");
  process.exit(1);
}
const claims = await mineWithOpenRouter(vtt, title);
if (!claims?.length) {
  console.error("OpenRouter extraction failed.");
  process.exit(1);
}
emitLedger({ video_id: videoId, title, speaker: "Unknown", slug: videoId }, claims, outDir);
